# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Comment\Model\Comment:
    type: entity
    repositoryClass: Kreta\Component\Comment\Repository\CommentRepository
    table: comment
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        createdAt:
            column: created_at
            type: datetime
        description:
            type: text
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
    manyToOne:
        issue:
            targetEntity: Kreta\Component\Issue\Model\Interfaces\IssueInterface
            joinColumn:
                name: issue_id
                referencedColumnName: id
                onDelete: CASCADE
        writtenBy:
            targetEntity: Kreta\Component\User\Model\Interfaces\UserInterface
            joinColumn:
                name: user_id
                referencedColumnName: id
