# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Comment\Model\Comment:
    exclusion_policy: ALL
    relations:
        -
            rel: issue
            href:
                route: get_issue
                parameters:
                    issueId: expr(object.getIssue().getId())
                absolute: true
            exclusion:
                groups: [commentList, comment]
        -
            rel: comments
            href:
                route: get_issues_comments
                parameters:
                    issueId: expr(object.getIssue().getId())
                absolute: true
            exclusion:
                groups: [commentList, comment]
    properties:
        id:
            expose: true
            groups: [commentList, comment]
        createdAt:
            expose: true
            groups: [commentList, comment]
        description:
            expose: true
            groups: [commentList, comment]
        updatedAt:
            expose: true
            groups: [commentList, comment]
        issue:
            expose: true
            groups: []
        writtenBy:
            expose: true
            groups: [commentList, comment]
