# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#### FORMS ####
    kreta_comment.form_handler.comment:
        parent: kreta_core.form_handler.handler
        arguments:
            - kreta_comment_comment_type

#### TYPES ####
    kreta_comment.form_type.comment:
        class: %kreta_comment.form_type.comment.class%
        arguments:
            - %kreta_comment.comment.class%
            - @kreta_comment.factory.comment
            - @security.token_storage
        tags:
            - { name: form.type, alias: 'kreta_comment_comment_type' }
